name: Release Windows Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller twitch_chat_to_3tene.py --name TwitchChatTo3tene.exe

      - name: Rename config.json
        run: ren config.json.template config.json

      - name: Create release archive
        run: |
          $tagName = "${{ github.ref_name }}"
          $zipName = "TwitchChatTo3tene-$tagName.zip"
          Compress-Archive -Path dist\TwitchChatTo3tene.exe\TwitchChatTo3tene.exe, dist\TwitchChatTo3tene.exe\_internal, LICENSE, README.md, config.json, emotion.json -DestinationPath $zipName

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./TwitchChatTo3tene-${{ github.ref_name }}.zip
          asset_name: TwitchChatTo3tene-${{ github.ref_name }}.zip
          asset_content_type: application/zip
